/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedHistoricoRouteRouteImport } from './routes/_authenticated/historico.route'
import { Route as AuthenticatedMaisRouteImport } from './routes/_authenticated/mais'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedHistoricoIndexRouteImport } from './routes/_authenticated/historico/index'
import { Route as AuthenticatedHistoricoDateRouteImport } from './routes/_authenticated/historico/$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRouteRoute =
  AuthenticatedHistoricoRouteRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaisRoute = AuthenticatedMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoIndexRoute =
  AuthenticatedHistoricoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHistoricoRouteRoute,
  } as any)
const AuthenticatedHistoricoDateRoute =
  AuthenticatedHistoricoDateRouteImport.update({
    id: '/$date',
    path: '/$date',
    getParentRoute: () => AuthenticatedHistoricoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/historico': typeof AuthenticatedHistoricoRouteRouteWithChildren
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/contas': typeof AuthenticatedContasRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/historico/$date': typeof AuthenticatedHistoricoDateRoute
  '/historico/': typeof AuthenticatedHistoricoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/contas': typeof AuthenticatedContasRoute
  '/mais': typeof AuthenticatedMaisRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/historico/$date': typeof AuthenticatedHistoricoDateRoute
  '/historico': typeof AuthenticatedHistoricoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRouteRouteWithChildren
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/mais': typeof AuthenticatedMaisRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/historico/$date': typeof AuthenticatedHistoricoDateRoute
  '/_authenticated/historico/': typeof AuthenticatedHistoricoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/historico'
    | '/calendario'
    | '/contas'
    | '/mais'
    | '/painel'
    | '/historico/$date'
    | '/historico/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/calendario'
    | '/contas'
    | '/mais'
    | '/painel'
    | '/historico/$date'
    | '/historico'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/historico'
    | '/_authenticated/calendario'
    | '/_authenticated/contas'
    | '/_authenticated/mais'
    | '/_authenticated/painel'
    | '/_authenticated/historico/$date'
    | '/_authenticated/historico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mais': {
      id: '/_authenticated/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AuthenticatedMaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico/': {
      id: '/_authenticated/historico/'
      path: '/'
      fullPath: '/historico/'
      preLoaderRoute: typeof AuthenticatedHistoricoIndexRouteImport
      parentRoute: typeof AuthenticatedHistoricoRouteRoute
    }
    '/_authenticated/historico/$date': {
      id: '/_authenticated/historico/$date'
      path: '/$date'
      fullPath: '/historico/$date'
      preLoaderRoute: typeof AuthenticatedHistoricoDateRouteImport
      parentRoute: typeof AuthenticatedHistoricoRouteRoute
    }
  }
}

interface AuthenticatedHistoricoRouteRouteChildren {
  AuthenticatedHistoricoDateRoute: typeof AuthenticatedHistoricoDateRoute
  AuthenticatedHistoricoIndexRoute: typeof AuthenticatedHistoricoIndexRoute
}

const AuthenticatedHistoricoRouteRouteChildren: AuthenticatedHistoricoRouteRouteChildren =
  {
    AuthenticatedHistoricoDateRoute: AuthenticatedHistoricoDateRoute,
    AuthenticatedHistoricoIndexRoute: AuthenticatedHistoricoIndexRoute,
  }

const AuthenticatedHistoricoRouteRouteWithChildren =
  AuthenticatedHistoricoRouteRoute._addFileChildren(
    AuthenticatedHistoricoRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoricoRouteRoute: typeof AuthenticatedHistoricoRouteRouteWithChildren
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedMaisRoute: typeof AuthenticatedMaisRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoricoRouteRoute:
    AuthenticatedHistoricoRouteRouteWithChildren,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedMaisRoute: AuthenticatedMaisRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
